# Generated by Django 3.2.5 on 2021-07-19 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='zipCode',
            field=models.IntegerField(default=1),
            preserve_default=False
        ),
    ]
