# Generated by Django 3.2.5 on 2021-07-25 01:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lang', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='zipCode',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='location',
            name='lat',
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='zipCode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='Coordinates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.coordinates'),
            preserve_default=False,
        ),
    ]
