# Generated by Django 3.2.5 on 2021-07-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(upload_to='static'),
        ),
    ]
