# Generated by Django 3.2.5 on 2021-07-31 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.coordinates'),
        ),
    ]
