# Generated by Django 3.2.5 on 2021-07-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210731_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
