# Generated by Django 2.2.13 on 2021-06-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lang', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=255)),
                ('zipCode', models.IntegerField()),
                ('mapGrid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='map_grids', to='location.MapGrid')),
            ],
        ),
    ]
